spring.application.name=smartcampus
server.port=8081
spring.config.import=optional:file:.env.properties,optional:file:./smartcampus/.env.properties

spring.datasource.url=jdbc:postgresql://localhost:5432/smartcampus
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:UniHelp123}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.security.admin-email=koffy.doggy@gmail.com
app.security.admin-password=12345
app.security.admin-user-id=ADMIN001
app.activation.otp-ttl-minutes=10
app.activation.max-otp-requests-before-flag=3
