package com.it3030.smartcampus.member1.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "resource_notifications")
public class ResourceNotification {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "resource_id")
    private EnhancedResource resource;

    @Column(name = "user_id", nullable = false)
    private String userId;

    @Column(name = "notification_type", nullable = false)
    @Enumerated(EnumType.STRING)
    private NotificationType notificationType;

    @Column(name = "title", nullable = false)
    private String title;

    @Column(name = "message", nullable = false, columnDefinition = "TEXT")
    private String message;

    @Column(name = "priority_level", nullable = false)
    @Enumerated(EnumType.STRING)
    private PriorityLevel priorityLevel = PriorityLevel.NORMAL;

    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.STRING)
    private NotificationStatus status = NotificationStatus.UNREAD;

    @Column(name = "delivery_method", nullable = false)
    @Enumerated(EnumType.STRING)
    private DeliveryMethod deliveryMethod = DeliveryMethod.IN_APP;

    @Column(name = "scheduled_at")
    private LocalDateTime scheduledAt;

    @Column(name = "sent_at")
    private LocalDateTime sentAt;

    @Column(name = "read_at")
    private LocalDateTime readAt;

    @Column(name = "expires_at")
    private LocalDateTime expiresAt;

    @Column(name = "action_required")
    private Boolean actionRequired = false;

    @Column(name = "action_url")
    private String actionUrl;

    @Column(name = "action_button_text")
    private String actionButtonText;

    @Column(name = "related_booking_id")
    private Long relatedBookingId;

    @Column(name = "related_maintenance_id")
    private Long relatedMaintenanceId;

    @Column(name = "related_rating_id")
    private Long relatedRatingId;

    @Column(name = "auto_generated", nullable = false)
    private Boolean autoGenerated = false;

    @Column(name = "template_used")
    private String templateUsed;

    @Column(name = "metadata", columnDefinition = "TEXT")
    private String metadata;

    @Column(name = "retry_count", nullable = false)
    private Integer retryCount = 0;

    @Column(name = "max_retries", nullable = false)
    private Integer maxRetries = 3;

    @Column(name = "last_retry_at")
    private LocalDateTime lastRetryAt;

    @Column(name = "delivery_status")
    @Enumerated(EnumType.STRING)
    private DeliveryStatus deliveryStatus = DeliveryStatus.PENDING;

    @Column(name = "error_message", columnDefinition = "TEXT")
    private String errorMessage;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    @Column(name = "updated_at")
    private LocalDateTime updatedAt = LocalDateTime.now();

    public enum NotificationType {
        BOOKING_CONFIRMED, BOOKING_REMINDER, BOOKING_CANCELLED, BOOKING_APPROVED, BOOKING_REJECTED,
        MAINTENANCE_SCHEDULED, MAINTENANCE_COMPLETED, MAINTENANCE_OVERDUE,
        RESOURCE_AVAILABLE, RESOURCE_UNAVAILABLE, RESOURCE_LOW_STOCK,
        PAYMENT_DUE, PAYMENT_OVERDUE, PAYMENT_CONFIRMED, REFUND_PROCESSED,
        RATING_REQUEST, SYSTEM_ALERT, ANNOUNCEMENT, SECURITY_ALERT,
        EQUIPMENT_ISSUE, ACCESS_GRANTED, ACCESS_DENIED, SCHEDULE_CHANGE
    }

    public enum PriorityLevel {
        LOW, NORMAL, HIGH, URGENT, CRITICAL
    }

    public enum NotificationStatus {
        UNREAD, READ, ARCHIVED, DELETED
    }

    public enum DeliveryMethod {
        IN_APP, EMAIL, SMS, PUSH_NOTIFICATION, WEBHOOK
    }

    public enum DeliveryStatus {
        PENDING, SENT, DELIVERED, FAILED, RETRYING
    }

    public ResourceNotification() {}

    public ResourceNotification(String userId, NotificationType notificationType, String title, String message) {
        this.userId = userId;
        this.notificationType = notificationType;
        this.title = title;
        this.message = message;
    }

    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public EnhancedResource getResource() { return resource; }
    public void setResource(EnhancedResource resource) { this.resource = resource; }

    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }

    public NotificationType getNotificationType() { return notificationType; }
    public void setNotificationType(NotificationType notificationType) { this.notificationType = notificationType; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getMessage() { return message; }
    public void setMessage(String message) { this.message = message; }

    public PriorityLevel getPriorityLevel() { return priorityLevel; }
    public void setPriorityLevel(PriorityLevel priorityLevel) { this.priorityLevel = priorityLevel; }

    public NotificationStatus getStatus() { return status; }
    public void setStatus(NotificationStatus status) { this.status = status; }

    public DeliveryMethod getDeliveryMethod() { return deliveryMethod; }
    public void setDeliveryMethod(DeliveryMethod deliveryMethod) { this.deliveryMethod = deliveryMethod; }

    public LocalDateTime getScheduledAt() { return scheduledAt; }
    public void setScheduledAt(LocalDateTime scheduledAt) { this.scheduledAt = scheduledAt; }

    public LocalDateTime getSentAt() { return sentAt; }
    public void setSentAt(LocalDateTime sentAt) { this.sentAt = sentAt; }

    public LocalDateTime getReadAt() { return readAt; }
    public void setReadAt(LocalDateTime readAt) { this.readAt = readAt; }

    public LocalDateTime getExpiresAt() { return expiresAt; }
    public void setExpiresAt(LocalDateTime expiresAt) { this.expiresAt = expiresAt; }

    public Boolean getActionRequired() { return actionRequired; }
    public void setActionRequired(Boolean actionRequired) { this.actionRequired = actionRequired; }

    public String getActionUrl() { return actionUrl; }
    public void setActionUrl(String actionUrl) { this.actionUrl = actionUrl; }

    public String getActionButtonText() { return actionButtonText; }
    public void setActionButtonText(String actionButtonText) { this.actionButtonText = actionButtonText; }

    public Long getRelatedBookingId() { return relatedBookingId; }
    public void setRelatedBookingId(Long relatedBookingId) { this.relatedBookingId = relatedBookingId; }

    public Long getRelatedMaintenanceId() { return relatedMaintenanceId; }
    public void setRelatedMaintenanceId(Long relatedMaintenanceId) { this.relatedMaintenanceId = relatedMaintenanceId; }

    public Long getRelatedRatingId() { return relatedRatingId; }
    public void setRelatedRatingId(Long relatedRatingId) { this.relatedRatingId = relatedRatingId; }

    public Boolean getAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(Boolean autoGenerated) { this.autoGenerated = autoGenerated; }

    public String getTemplateUsed() { return templateUsed; }
    public void setTemplateUsed(String templateUsed) { this.templateUsed = templateUsed; }

    public String getMetadata() { return metadata; }
    public void setMetadata(String metadata) { this.metadata = metadata; }

    public Integer getRetryCount() { return retryCount; }
    public void setRetryCount(Integer retryCount) { this.retryCount = retryCount; }

    public Integer getMaxRetries() { return maxRetries; }
    public void setMaxRetries(Integer maxRetries) { this.maxRetries = maxRetries; }

    public LocalDateTime getLastRetryAt() { return lastRetryAt; }
    public void setLastRetryAt(LocalDateTime lastRetryAt) { this.lastRetryAt = lastRetryAt; }

    public DeliveryStatus getDeliveryStatus() { return deliveryStatus; }
    public void setDeliveryStatus(DeliveryStatus deliveryStatus) { this.deliveryStatus = deliveryStatus; }

    public String getErrorMessage() { return errorMessage; }
    public void setErrorMessage(String errorMessage) { this.errorMessage = errorMessage; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }

    // Business logic methods
    public boolean isExpired() {
        return expiresAt != null && expiresAt.isBefore(LocalDateTime.now());
    }

    public boolean canRetry() {
        return retryCount < maxRetries && deliveryStatus == DeliveryStatus.FAILED;
    }

    public void markAsRead() {
        this.status = NotificationStatus.READ;
        this.readAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    public void markAsSent() {
        this.sentAt = LocalDateTime.now();
        this.deliveryStatus = DeliveryStatus.SENT;
        this.updatedAt = LocalDateTime.now();
    }

    public void markAsDelivered() {
        this.deliveryStatus = DeliveryStatus.DELIVERED;
        this.updatedAt = LocalDateTime.now();
    }

    public void markAsFailed(String errorMessage) {
        this.deliveryStatus = DeliveryStatus.FAILED;
        this.errorMessage = errorMessage;
        this.retryCount++;
        this.lastRetryAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    public boolean isHighPriority() {
        return priorityLevel == PriorityLevel.HIGH || priorityLevel == PriorityLevel.URGENT || priorityLevel == PriorityLevel.CRITICAL;
    }

    public boolean requiresAction() {
        return actionRequired && (actionUrl != null || actionButtonText != null);
    }
}
