package com.it3030.smartcampus.member1.repository;

import com.it3030.smartcampus.member1.model.ResourceNotification;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Repository
public interface ResourceNotificationRepository extends JpaRepository<ResourceNotification, Long> {

    List<ResourceNotification> findByUserId(String userId);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.resource.id = :resourceId")
    List<ResourceNotification> findNotificationsByResourceId(@Param("resourceId") Long resourceId);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.status = :status ORDER BY n.createdAt DESC")
    List<ResourceNotification> findByUserIdAndStatus(@Param("userId") String userId, @Param("status") ResourceNotification.NotificationStatus status);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.status = 'UNREAD' ORDER BY n.createdAt DESC")
    List<ResourceNotification> findUnreadNotificationsForUser(@Param("userId") String userId);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.status = 'UNREAD' ORDER BY n.createdAt DESC")
    Page<ResourceNotification> findUnreadNotificationsForUserPaginated(@Param("userId") String userId, Pageable pageable);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.priorityLevel = :priorityLevel ORDER BY n.createdAt DESC")
    List<ResourceNotification> findByUserIdAndPriorityLevel(@Param("userId") String userId, @Param("priorityLevel") ResourceNotification.PriorityLevel priorityLevel);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.notificationType = :type ORDER BY n.createdAt DESC")
    List<ResourceNotification> findByUserIdAndType(@Param("userId") String userId, @Param("type") ResourceNotification.NotificationType type);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.deliveryMethod = :method ORDER BY n.createdAt DESC")
    List<ResourceNotification> findByUserIdAndDeliveryMethod(@Param("userId") String userId, @Param("method") ResourceNotification.DeliveryMethod method);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.deliveryStatus = :status ORDER BY n.createdAt DESC")
    List<ResourceNotification> findByUserIdAndDeliveryStatus(@Param("userId") String userId, @Param("status") ResourceNotification.DeliveryStatus status);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.scheduledAt IS NOT NULL AND n.scheduledAt <= :now AND n.deliveryStatus = 'PENDING'")
    List<ResourceNotification> findScheduledNotificationsToSend(@Param("now") LocalDateTime now);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.expiresAt IS NOT NULL AND n.expiresAt <= :now AND n.status != 'DELETED'")
    List<ResourceNotification> findExpiredNotifications(@Param("now") LocalDateTime now);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.deliveryStatus = 'FAILED' AND n.retryCount < n.maxRetries")
    List<ResourceNotification> findNotificationsToRetry();
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.relatedBookingId = :bookingId")
    List<ResourceNotification> findByRelatedBookingId(@Param("bookingId") Long bookingId);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.relatedMaintenanceId = :maintenanceId")
    List<ResourceNotification> findByRelatedMaintenanceId(@Param("maintenanceId") Long maintenanceId);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.relatedRatingId = :ratingId")
    List<ResourceNotification> findByRelatedRatingId(@Param("ratingId") Long ratingId);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.actionRequired = true AND n.status = 'UNREAD'")
    List<ResourceNotification> findUnreadActionRequiredNotifications();
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.actionRequired = true AND n.status = 'UNREAD'")
    List<ResourceNotification> findUnreadActionRequiredNotificationsForUser(@Param("userId") String userId);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.autoGenerated = true")
    List<ResourceNotification> findAutoGeneratedNotifications();
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.templateUsed = :templateName")
    List<ResourceNotification> findByTemplate(@Param("templateName") String templateName);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.createdAt >= :startDate AND n.createdAt <= :endDate")
    List<ResourceNotification> findNotificationsForUserInDateRange(@Param("userId") String userId, @Param("startDate") LocalDateTime startDate, @Param("endDate") LocalDateTime endDate);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.resource.id = :resourceId AND n.createdAt >= :startDate AND n.createdAt <= :endDate")
    List<ResourceNotification> findNotificationsForResourceInDateRange(@Param("resourceId") Long resourceId, @Param("startDate") LocalDateTime startDate, @Param("endDate") LocalDateTime endDate);
    
    @Query("SELECT COUNT(n) FROM ResourceNotification n WHERE n.userId = :userId AND n.status = 'UNREAD'")
    long countUnreadNotificationsForUser(@Param("userId") String userId);
    
    @Query("SELECT COUNT(n) FROM ResourceNotification n WHERE n.userId = :userId AND n.status = 'UNREAD' AND n.priorityLevel = 'HIGH'")
    long countHighPriorityUnreadNotificationsForUser(@Param("userId") String userId);
    
    @Query("SELECT COUNT(n) FROM ResourceNotification n WHERE n.userId = :userId AND n.actionRequired = true AND n.status = 'UNREAD'")
    long countUnreadActionRequiredNotificationsForUser(@Param("userId") String userId);
    
    @Query("SELECT COUNT(n) FROM ResourceNotification n WHERE n.deliveryStatus = 'FAILED'")
    long countFailedNotifications();
    
    @Query("SELECT COUNT(n) FROM ResourceNotification n WHERE n.notificationType = :type")
    long countNotificationsByType(@Param("type") ResourceNotification.NotificationType type);
    
    @Query("SELECT COUNT(n) FROM ResourceNotification n WHERE n.priorityLevel = :priorityLevel")
    long countNotificationsByPriorityLevel(@Param("priorityLevel") ResourceNotification.PriorityLevel priorityLevel);
    
    @Query("SELECT COUNT(n) FROM ResourceNotification n WHERE n.deliveryMethod = :method")
    long countNotificationsByDeliveryMethod(@Param("method") ResourceNotification.DeliveryMethod method);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND (n.title LIKE %:searchTerm% OR n.message LIKE %:searchTerm%)")
    List<ResourceNotification> searchNotificationsForUser(@Param("userId") String userId, @Param("searchTerm") String searchTerm);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.createdAt >= :date ORDER BY n.createdAt DESC")
    List<ResourceNotification> findRecentNotificationsForUser(@Param("userId") String userId, @Param("date") LocalDateTime date);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.priorityLevel IN :priorityLevels ORDER BY n.createdAt DESC")
    List<ResourceNotification> findByUserIdAndPriorityLevels(@Param("userId") String userId, @Param("priorityLevels") List<ResourceNotification.PriorityLevel> priorityLevels);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.notificationType IN :types ORDER BY n.createdAt DESC")
    List<ResourceNotification> findByUserIdAndTypes(@Param("userId") String userId, @Param("types") List<ResourceNotification.NotificationType> types);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.resource.id = :resourceId AND n.userId = :userId ORDER BY n.createdAt DESC")
    List<ResourceNotification> findNotificationsForResourceAndUser(@Param("resourceId") Long resourceId, @Param("userId") String userId);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.resource.id = :resourceId AND n.userId = :userId AND n.status = 'UNREAD'")
    List<ResourceNotification> findUnreadNotificationsForResourceAndUser(@Param("resourceId") Long resourceId, @Param("userId") String userId);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.sentAt >= :startDate AND n.sentAt <= :endDate")
    List<ResourceNotification> findSentNotificationsInDateRange(@Param("startDate") LocalDateTime startDate, @Param("endDate") LocalDateTime endDate);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.readAt >= :startDate AND n.readAt <= :endDate")
    List<ResourceNotification> findReadNotificationsInDateRange(@Param("startDate") LocalDateTime startDate, @Param("endDate") LocalDateTime endDate);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.deliveryStatus = 'DELIVERED' AND n.readAt IS NULL")
    List<ResourceNotification> findDeliveredButUnreadNotifications();
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.expiresAt > :now AND n.status != 'DELETED' ORDER BY n.expiresAt ASC")
    List<ResourceNotification> findActiveNotificationsForUser(@Param("userId") String userId, @Param("now") LocalDateTime now);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.status != 'DELETED' ORDER BY n.createdAt DESC")
    Page<ResourceNotification> findAllActiveNotificationsForUserPaginated(@Param("userId") String userId, Pageable pageable);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.status = 'ARCHIVED' ORDER BY n.createdAt DESC")
    List<ResourceNotification> findArchivedNotificationsForUser(@Param("userId") String userId);
    
    @Query("SELECT COUNT(n) FROM ResourceNotification n WHERE n.createdAt >= :date")
    long countNotificationsSince(@Param("date") LocalDateTime date);
    
    @Query("SELECT COUNT(n) FROM ResourceNotification n WHERE n.userId = :userId AND n.createdAt >= :date")
    long countNotificationsForUserSince(@Param("userId") String userId, @Param("date") LocalDateTime date);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.resource.id = :resourceId AND n.userId = :userId AND n.priorityLevel = :priorityLevel ORDER BY n.createdAt DESC")
    List<ResourceNotification> findNotificationsForResourceUserAndPriority(@Param("resourceId") Long resourceId, @Param("userId") String userId, @Param("priorityLevel") ResourceNotification.PriorityLevel priorityLevel);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.deliveryStatus = 'DELIVERED' AND n.readAt IS NULL AND n.createdAt >= :date")
    List<ResourceNotification> findUnreadDeliveredNotificationsForUserSince(@Param("userId") String userId, @Param("date") LocalDateTime date);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.resource.id = :resourceId AND n.notificationType = :type ORDER BY n.createdAt DESC")
    List<ResourceNotification> findNotificationsForResourceAndType(@Param("resourceId") Long resourceId, @Param("type") ResourceNotification.NotificationType type);
    
    @Query("SELECT n FROM ResourceNotification n WHERE n.userId = :userId AND n.autoGenerated = :autoGenerated ORDER BY n.createdAt DESC")
    List<ResourceNotification> findByUserIdAndAutoGenerated(@Param("userId") String userId, @Param("autoGenerated") Boolean autoGenerated);
}
